### ISSUE TITLE
pytorch0.4.0报错

### ISSUE THREAD

**Issue by bamtercelboo** [bamtercelboo/pytorch_NER_BiLSTM_CNN_CRF#2]
pytorch0.4.0报错
python==3.5.2
cuda==8.0

在运行sh run_train_p.sh出现以下错误，请问怎么解决呢？谢谢！
## The 1 Epoch, All 1000 Epochs ! ##
/home/admination/.virtualenvs_dl/ll/lib/python3.5/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
now lr is 0.015
Train Time 0.436Traceback (most recent call last):
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/main.py", line 154, in <module>
    main()
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/main.py", line 91, in main
    start_train(train_iter, dev_iter, test_iter, model, config)
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/main.py", line 45, in start_train
    t.train()
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/trainer.py", line 204, in train
    self.eval(model=self.model, epoch=epoch, config=self.config)
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/trainer.py", line 217, in eval
    self.eval_batch(self.dev_iter, model, self.dev_eval, self.best_score, epoch, config, test=False)
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/trainer.py", line 272, in eval_batch
    path_score, best_paths = model.crf_layer(logit, mask)
  File "/home/admination/.virtualenvs_dl/ll/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/models/CRF.py", line 207, in forward
    path_score, best_path = self._viterbi_decode(feats, mask)
  File "/home/admination/na_na/new-ner/pytorch_NER_BiLSTM_CNN_CRF-master/models/CRF.py", line 196, in _viterbi_decode
    decode_idx[idx] = pointer.data
RuntimeError: expand(torch.cuda.LongTensor{[16, 1]}, size=[16]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

**Comment by bamtercelboo** [comment]
pytorch0.4.0的这个问题，把decode_idx[idx] = pointer.data 这个改成 decode_idx[idx] = pointer.data.squeeze(-1)
